FROM node:20


WORKDIR /app

COPY package*.json .

RUN apt-get update && apt-get upgrade

COPY package*.json ./


RUN npm install


COPY . .

ENV WATCHPACK_POLLING true

# RUN npm run build

EXPOSE 3000

# RUN yarn build

CMD ["npm","run","dev"]
